[package]
name = "sqlx_migrator"
version = "0.1.0"
edition = "2021"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/sqlx_migrator"
repository = "https://github.com/iamsauravsharma/sqlx_migrator"
license = "MIT"
readme = "README.MD"

[dependencies]
sqlx = { version = "0.5.13", default-features = false }
async-trait = "0.1.53"
tracing = { version = "0.1.34", optional = true }
thiserror = "1.0.31"
clap = { version = "3.1.18", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1.18.2", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.11"

[features]
default = ["cli", "runtime-tokio-native-tls", "postgres", "tracing"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
cli = ["clap"]

[[example]]
name = "postgres"
path = "examples/postgres/main.rs"
required-features = ["postgres", "runtime-tokio-native-tls"]

[[example]]
name = "sqlite"
path = "examples/sqlite/main.rs"
required-features = ["sqlite", "runtime-tokio-native-tls"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
