[package]
name = "sqlx_migrator"
version = "0.2.1"
edition = "2021"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/sqlx_migrator"
repository = "https://github.com/iamsauravsharma/sqlx_migrator"
description = "Migrator for writing sqlx migration using Rust instead of SQL"
license = "MIT"
readme = "README.MD"

[dependencies]
sqlx = { version = "0.6.2", default-features = false, features = [
    "macros",
    "chrono",
] }
async-trait = "0.1.58"
tracing = { version = "0.1.37", optional = true }
thiserror = "1.0.37"
clap = { version = "4.0.18", features = ["derive"], optional = true }
chrono = "0.4.22"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }

[features]
default = ["cli", "tracing"]
tracing = ["dep:tracing"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
cli = ["dep:clap"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[[example]]
name = "postgres"
path = "examples/postgres/main.rs"
required-features = ["postgres", "runtime-tokio-native-tls"]

[[example]]
name = "sqlite"
path = "examples/sqlite/main.rs"
required-features = ["sqlite", "runtime-tokio-native-tls"]

[package.metadata.docs.rs]
features = ["postgres", "sqlite", "runtime-tokio-native-tls"]
rustdoc-args = ["--cfg", "docsrs"]
